### ISSUE TITLE
Many questions about how to operate

### ISSUE THREAD

**Issue by Ask-sola** [jackwaudby/ldbc-snb-implementations#3]
Hello, I am trying to run your project, but there seem to be many things that I haven't figured out and can't get started, so I have to take the liberty of asking

I have never used JanusGraph as a database, but now I need to run through an ldbc implementation of gremlin as a reference. So I may have asked some seemingly foolish questions, please forgive me.

The first step is to set the path of the janusgraph“export JANUSGRAPH_HOME=`pwd`”, where is the repo?
I searched directly and found this repo “https://github.com/JanusGraph/janusgraph” ，but it doesn't seem like it should be in this position  .

The next question is what is the directory for the datagen, where can I find it? Should you use "spark_based" or "hadoop_based", "bi mode" or "interactive mode"? What is the splitting method for the dataset? I didn't see the script you generated the data from, it seems that you directly loda the data, so I'm not sure which dataset type you should use specifically.

Regarding the './delete db. sh' script, it seems that you want to delete something from the repo of Janusgraph, but in the “https://github.com/JanusGraph/janusgraph” There is no /DB folder in the obtained repo, so I think I may have a problem understanding 'janusgraph's repo'

Next, I was looking at the command in "./load validation. sh" and he first executed the following code:
Rm - Rf ${LDBC_SNB-DATAGEN_HOME}/social_network ${LDBC_SNB-DATAGEN_HOME}/substitution_parameters
And 'LDBC_SNB-DATAGEN_HOME' points to the data generator, it is obvious that the folder concept and project of the data generator here“ https://github.com/ldbc/ldbc_snb_interactive_impls/tree/main ”It's completely different, so I'm not sure how to obtain the LDBC I need to run this project_ SNB_ DATAGEN_ HOME. It seems that the dataset you generated contains' social_network 'and' substitution_parameters', but through“ https://github.com/ldbc/ldbc_snb_interactive_impls/tree/main ”The generated dataset does not have this component at all

For './complete loader. sh', he called a CompleteLoader class, but I couldn't find it

From './run validation. sh', it seems that there is a jar package 'uber janusgraph-1.0-SNAPSHOT. jar' present. However, I am not sure what method to use to build the entire project or how to obtain the necessary jar packages to run this project

**Comment by jackwaudby** [comment]
Hi @Ask-sola sorry this repository is not maintained.
